apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "11"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"auth-service","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"auth-service"}},"template":{"metadata":{"labels":{"app":"auth-service"}},"spec":{"containers":[{"env":[{"name":"ALLOWED_ORIGINS","value":"https://perci.goyap.ai,https://app.goyap.ai,https://goyap.ai,http://localhost:8100"}],"envFrom":[{"secretRef":{"name":"auth-secrets"}},{"secretRef":{"name":"mongodb-secrets"}}],"image":"486276252245.dkr.ecr.us-east-1.amazonaws.com/yap-auth-service:cors-fix-v1","livenessProbe":{"failureThreshold":6,"httpGet":{"path":"/healthz","port":8080},"initialDelaySeconds":15,"periodSeconds":20,"timeoutSeconds":5},"name":"auth","ports":[{"containerPort":8080}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/healthz","port":8080},"initialDelaySeconds":5,"periodSeconds":10,"timeoutSeconds":5},"resources":{"limits":{"cpu":"200m","memory":"256Mi"},"requests":{"cpu":"100m","memory":"128Mi"}}}]}}}}
  creationTimestamp: "2025-06-21T15:50:06Z"
  generation: 11
  name: auth-service
  namespace: default
  resourceVersion: "10145837"
  uid: b4d5d0d1-5bff-4176-964b-bf0cf9f51995
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: auth-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-07-02T16:11:30-04:00"
      creationTimestamp: null
      labels:
        app: auth-service
    spec:
      containers:
      - image: 486276252245.dkr.ecr.us-east-1.amazonaws.com/yap-auth-service:latest
        imagePullPolicy: Always
        name: auth-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - env:
        - name: ALLOWED_ORIGINS
          value: https://delta-sandbox-7k3m.goyap.ai,https://app.goyap.ai,https://goyap.ai,http://localhost:8100
        envFrom:
        - secretRef:
            name: auth-secrets
        - secretRef:
            name: mongodb-secrets
        image: 486276252245.dkr.ecr.us-east-1.amazonaws.com/yap-auth-service:cors-fix-v1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 5
        name: auth
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2025-06-21T15:50:06Z"
    lastUpdateTime: "2025-07-02T20:13:05Z"
    message: ReplicaSet "auth-service-b567878d6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-07-02T20:13:31Z"
    lastUpdateTime: "2025-07-02T20:13:31Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 11
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
