global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'tts-service'
    static_configs:
      - targets: ['tts-service:8002']  # Using the service name defined in docker-compose

  - job_name: 'triton-server'
    metrics_path: /metrics
    static_configs:
      - targets: ['triton-server:8002']
