apiVersion: batch/v1
kind: Job
metadata:
  name: resize-gpu-node-fs
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-10-0-1-36.ec2.internal
      hostPID: true
      containers:
      - name: resizer
        image: amazon/aws-cli:latest
        command: ["/bin/sh"]
        args:
          - -c
          - |
            yum update -y && yum install -y util-linux e2fsprogs
            if mountpoint -q /host; then
              echo "Expanding partition..."
              growpart /host/dev/nvme0n1 1 || true
              echo "Resizing filesystem..."
              resize2fs /host/dev/nvme0n1p1 || true
              df -h /host
            else
              echo "Host filesystem not mounted"
            fi
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-dev
          mountPath: /host/dev
        - name: host-root
          mountPath: /host
          mountPropagation: Bidirectional
      volumes:
      - name: host-dev
        hostPath:
          path: /dev
      - name: host-root
        hostPath:
          path: /
      restartPolicy: Never
  backoffLimit: 3
