apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-chat-service
  labels:
    app: ai-chat-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-chat-service
  template:
    metadata:
      labels:
        app: ai-chat-service
    spec:
      containers:
        - name: ai-chat-service
          image: 486276252245.dkr.ecr.us-east-1.amazonaws.com/yap-ai-chat-service:latest
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - secretRef:
                name: ai-services-secrets
            - secretRef:
                name: database-cache-secrets  # For Redis/MongoDB access
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "8080"
            - name: FRONTEND_URL
              value: "https://perci.goyap.ai"
            - name: PRONUNCIATION_SCORER_URL
              value: "http://pronunciation-scorer:50052"
            - name: TTS_SERVICE_URL
              value: "http://tts-service:50053"
            - name: AI_SERVICE_URL
              value: "http://ai-service:8080"
            - name: BLOCKCHAIN_PROGRESS_SERVICE_URL
              value: "http://blockchain-progress-service:8080"
            - name: PROFILE_SERVICE_URL
              value: "http://profile:3003"
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ai-chat-service
  labels:
    app: ai-chat-service
spec:
  selector:
    app: ai-chat-service
  ports:
    - port: 80
      targetPort: 8080
      name: http
