# NOTE: ai-service might be integrated into ai-chat-service
# Commenting out until we verify the architecture
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: ai-service
  labels:
    app: ai-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
        - name: ai-service
          image: 486276252245.dkr.ecr.us-east-1.amazonaws.com/yap-ai-service:latest
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - secretRef:
                name: ai-services-secrets
          resources:
            requests:
              cpu: "300m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
  labels:
    app: ai-service
spec:
  selector:
    app: ai-service
  ports:
    - port: 80
      targetPort: 8080
      name: http
