apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
type: Opaque
stringData:
  clientId: "BKgE24eONnA63tZkrB2DytRZ9f6KzYQL2diPgB9YWMlDDiwsrOpFk1NTAXtx71HR3o9bwABGovS8ZiFtmbyrJP4"
  # Add any other secrets your auth service needs
  APP_JWT_SECRET: "lnk9JUvtvH5LwZK8BMhI3WPL1a2DlFt+rDrqNE/l8JxViTXGKcEmzQ+9UeGqrH0SYpgK+3KCZcx4brcO5QzKMQ=="