apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1  # Reduced to 1 for local development
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: auth-service  # Local image name without ECR URI
          ports:
            - containerPort: 8080
          env:
            - name: WEB3AUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: clientId
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
