apiVersion: apps/v1
kind: Deployment
metadata:
  name: collaboration-service
  labels:
    app: collaboration-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: collaboration-service
  template:
    metadata:
      labels:
        app: collaboration-service
    spec:
      containers:
        - name: collaboration-service
          image: 486276252245.dkr.ecr.us-east-1.amazonaws.com/yap-collaboration-service:latest
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - secretRef:
                name: database-cache-secrets  # For Redis/MongoDB access
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "8080"
            - name: AI_SERVICE_URL
              value: "http://ai-service:8080"
            - name: PROFILE_SERVICE_URL
              value: "http://profile-service:8080"
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: collaboration-service
  labels:
    app: collaboration-service
spec:
  selector:
    app: collaboration-service
  ports:
    - port: 80
      targetPort: 8080
      name: http
