apiVersion: v1
kind: Secret
metadata:
  name: database-cache-secrets
  namespace: default
type: Opaque
data:
  # Redis Configuration (base64 encoded)
  REDIS_URL: cmVkaXM6Ly9yZWRpcy1zZXJ2aWNlOjYzNzk=
  
  # MongoDB options for production Atlas cluster
  MONGODB_OPTIONS: cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q1kw
  
  # Database names for different services
  MONGO_DB_NAME: eWFw
  AI_CHAT_DB_NAME: eWFw
  LEARNING_DB_NAME: eWFw
  PROFILE_DB_NAME: eWFw
  
  # Cache configuration
  CACHE_TTL: MzYwMA==
  CACHE_MAX_SIZE: NTAwMA==
  
  # Session configuration
  SESSION_TIMEOUT_MS: MzYwMDAwMA==
  MAX_SESSIONS_PER_USER: MTA=
