apiVersion: apps/v1
kind: Deployment
metadata: { name: grammar-service }
spec:
  replicas: 2
  selector: { matchLabels: { app: grammar-service } }
  template:
    metadata: { labels: { app: grammar-service } }
    spec:
      containers:
        - name: grammar
          image: grammar-service:latest
          ports: [{ containerPort: 8000, name: http }]
          resources:
            requests: { cpu: "250m", memory: "256Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }
---
apiVersion: v1
kind: Service
metadata: { name: grammar-service }
spec:
  selector: { app: grammar-service }
  ports:
    - port: 80
      targetPort: 8000
      name: http
