apiVersion: apps/v1
kind: Deployment
metadata: { name: learning-service }
spec:
  replicas: 2
  selector: { matchLabels: { app: learning-service } }
  template:
    metadata: { labels: { app: learning-service } }
    spec:
      containers:
        - name: learning
          image: 486276252245.dkr.ecr.us-east-1.amazonaws.com/yap-learning-service:api-prefix-fix
          ports: [{ containerPort: 8080 }]
          envFrom:
            - secretRef: { name: profile-secrets }    # brings APP_JWT_SECRET
            - secretRef: { name: mongodb-secrets }    # brings MONGO_URI and MONGO_DB_NAME
          env:
            - name: ALLOWED_ORIGINS
              value: "https://perci.goyap.ai,https://app.goyap.ai,https://goyap.ai,http://localhost:3000"
---
apiVersion: v1
kind: Service
metadata: { name: learning-service }
spec:
  selector: { app: learning-service }
  ports:
    - port: 80
      targetPort: 8080
      name: http
