apiVersion: v1
kind: ServiceAccount
metadata:
  name: profile-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<AWS_ACCOUNT_ID>:role/yap-profile-iam-role
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service
  labels:
    app: profile
spec:
  replicas: 2
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      serviceAccountName: profile-sa
      containers:
        - name: profile
          image: profile-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: AWS_REGION
              value: "us-east-1"
            - name: DDB_TABLE
              value: "Profiles"
          envFrom:
            - secretRef:
                name: profile-secrets
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
  labels:
    app: profile
spec:
  type: ClusterIP
  selector:
    app: profile
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
