apiVersion: v1
kind: ServiceAccount
metadata:
  name: profile-sa
  annotations:
    eks.amazonaws.com/role-arn: ${aws_iam_role.offchain_profile_role.arn}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service
  labels:
    app: profile
spec:
  replicas: 2
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      serviceAccountName: profile-sa
      containers:
        - name: profile
          image: 486276252245.dkr.ecr.us-east-1.amazonaws.com/yap-profile-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: profile-secrets
            - secretRef:
                name: mongodb-secrets
            - configMapRef:
                name: profile-config
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
  labels:
    app: profile
spec:
  type: ClusterIP
  selector:
    app: profile
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
