apiVersion: apps/v1
kind: Deployment
metadata: { name: pronunciation-scorer }
spec:
  replicas: 2
  selector: { matchLabels: { app: pronunciation-scorer } }
  template:
    metadata: { labels: { app: pronunciation-scorer } }
    spec:
      containers:
        - name: pronunciation-scorer
          image: 486276252245.dkr.ecr.us-east-1.amazonaws.com/yap-pronunciation-scorer:20250624-144744  # Fixed grpc_interceptor dependency
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 50052, name: grpc }]
          resources:
            requests: { cpu: "150m", memory: "256Mi" }
            limits:   { cpu: "300m", memory: "512Mi" }
---
apiVersion: v1
kind: Service
metadata: { name: pronunciation-scorer }
spec:
  selector: { app: pronunciation-scorer }
  ports:
    - port: 50052
      targetPort: 50052
      name: grpc
