apiVersion: v1
kind: Secret
metadata:
  name: service-config-secrets
  namespace: default
type: Opaque
data:
  # Service URLs for internal EKS communication (base64 encoded)
  # Voice Score Service URL
  VOICE_SCORE_SERVICE_URL: aHR0cDovL3ZvaWNlLXNjb3JlLXNlcnZpY2U6ODA4MA==
  
  # TTS Service URL  
  TTS_SERVICE_URL: aHR0cDovL3R0cy1zZXJ2aWNlOjgwODA=
  
  # Learning Service URL
  LEARNING_SERVICE_URL: aHR0cDovL2xlYXJuaW5nLXNlcnZpY2U6MzAwMQ==
  
  # AI Service URL
  AI_SERVICE_URL: aHR0cDovL2FpLXNlcnZpY2U6ODA4MA==
  
  # Assessment Service URL
  ASSESSMENT_SERVICE_URL: aHR0cDovL2Fzc2Vzc21lbnQtc2VydmljZTo4MDgw
  
  # Profile Service URL
  PROFILE_SERVICE_URL: aHR0cDovL3Byb2ZpbGUtc2VydmljZTo4MDgw
  
  # Shared Service URL
  SHARED_SERVICE_URL: aHR0cDovL3NoYXJlZC1zZXJ2aWNlOjgwODA=
  
  # Gateway Service URL
  GATEWAY_SERVICE_URL: aHR0cDovL2dhdGV3YXktc2VydmljZTo4MDgw
  
  # Frontend URL for CORS (update for production domain)
  FRONTEND_URL: aHR0cHM6Ly95YXAuYXBw
  
  # Allowed origins for CORS (comma-separated, base64 encoded)
  ALLOWED_ORIGINS: aHR0cHM6Ly95YXAuYXBwLGh0dHBzOi8vd3d3LnlhcC5hcHAsaHR0cDovL2xvY2FsaG9zdDozMDAw

---
# Instructions:
# 1. Update FRONTEND_URL and ALLOWED_ORIGINS with your actual production domain
# 2. Service URLs are for internal EKS cluster communication
# 3. To encode: echo -n "your-url" | base64
# 4. Apply to cluster: kubectl apply -f service-config-secrets.yaml
