apiVersion: apps/v1
kind: Deployment
metadata: 
  name: tts-service
  labels:
    app: tts-service
    service: tts-service
spec:
  replicas: 2
  selector: { matchLabels: { app: tts-service } }
  template:
    metadata: { labels: { app: tts-service } }
    spec:
      containers:
        - name: tts-service
          image: 486276252245.dkr.ecr.us-east-1.amazonaws.com/yap-tts-service:latest  # Updated with cascading fallback TTS providers
          imagePullPolicy: Always
          ports: 
            - containerPort: 50053
              name: grpc
            - containerPort: 8002
              name: metrics
          env:
            - name: GRPC_PORT
              value: "50053"
            - name: METRICS_PORT
              value: "8002"
            - name: TTS_PROVIDER
              value: "aws"  # Primary provider: AWS Polly (new fallback order)
            - name: USE_AZURE_TTS
              value: "true"
            - name: AZURE_SPEECH_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-services-secrets
                  key: AZURE_SPEECH_KEY
                  optional: false
            - name: AZURE_SERVICE_REGION
              value: "eastus"
            - name: USE_FALLBACK_PROVIDER
              value: "true"
            - name: FALLBACK_TTS_PROVIDER
              value: "aws"  # Fallback provider: aws
            - name: USE_AWS_POLLY
              value: "true"
            - name: USE_GOOGLE_TTS
              value: "true"
            - name: AWS_REGION
              value: "us-east-1"
            - name: S3_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: yap-config
                  key: tts_s3_bucket
                  optional: true
            - name: USE_ALIGNMENT_SERVICE
              value: "true"
            - name: ALIGNMENT_SERVICE_HOST
              value: "alignment-service"
            - name: ALIGNMENT_SERVICE_PORT
              value: "50051"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: ai-services-secrets
                  key: AWS_ACCESS_KEY_ID
                  optional: true
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-services-secrets
                  key: AWS_SECRET_ACCESS_KEY
                  optional: true
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"  # Will fail gracefully if not available
            - name: KAFKA_ENABLED
              value: "false"  # Disable Kafka for now
            - name: USE_HTTP_FEEDBACK_API
              value: "false"  # Disable HTTP feedback API for now
          resources:
            requests: { cpu: "200m", memory: "512Mi" }
            limits:   { cpu: "500m",  memory: "1Gi" }
          readinessProbe:
            tcpSocket:
              port: 50053
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 50053
            initialDelaySeconds: 15
            periodSeconds: 15
          volumeMounts:
            - name: tts-storage
              mountPath: /app/models
              readOnly: false
      volumes:
        - name: tts-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata: 
  name: tts-service
  labels:
    app: tts-service
    service: tts-service
spec:
  selector: { app: tts-service }
  ports:
    - port: 50053
      targetPort: 50053
      name: grpc
    - port: 8002
      targetPort: 8002
      name: metrics
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tts-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tts-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tts-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
