apiVersion: apps/v1
kind: Deployment
metadata: { name: tts-service }
spec:
  replicas: 2
  selector: { matchLabels: { app: tts-service } }
  template:
    metadata: { labels: { app: tts-service } }
    spec:
      containers:
        - name: tts-service
          image: tts-service  # For local development with Skaffold
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 50053, name: grpc }]
          resources:
            requests: { cpu: "500m", memory: "1Gi" }
            limits:   { cpu: "1",    memory: "2Gi" }
---
apiVersion: v1
kind: Service
metadata: { name: tts-service }
spec:
  selector: { app: tts-service }
  ports:
    - port: 50053
      targetPort: 50053
      name: grpc
