apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
type: Opaque
stringData:
  DYNAMIC_ENV_ID: "382dd2f1-418f-443b-bb03-6b3f98dc7d12" # Dynamic Server Environment ID
  DYNAMIC_API_KEY: "dyn_waH52bqtjueEcRLrHLcSfvCVhm2jZxSyv2MCl24XumHJt8ZOg119sLcl" # Dynamic Server API Key
  APP_JWT_SECRET: "lnk9JUvtvH5LwZK8BMhI3WPL1a2DlFt+rDrqNE/l8JxViTXGKcEmzQ+9UeGqrH0SYpgK+3KCZcx4brcO5QzKMQ=="
  APP_REFRESH_SECRET: "lnk9JUvtvH5LwZK8BMhI3WPL1a2DlFt+rDrqNE/l8JxViTXGKcEmzQ+9UeGqrH0SYpgK+3KCZcx4brcO5QzKMQ==_refresh"
  ENVIRONMENT_ID: "382dd2f1-418f-443b-bb03-6b3f98dc7d12"
  INTERNAL_SERVICE_SECRET: "internal-service-secret-2025-secure-yap-backend"
