apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
type: Opaque
stringData:
  # Production connection string should be provided by your MongoDB provider
  # For example: mongodb+srv://username:password@cluster.mongodb.net/yap
  MONGO_URI: "mongodb+srv://yap-backend:sipwid-cemnYj-doqto2@cy0.uvp0w.mongodb.net/?retryWrites=true&w=majority&appName=CY0"
  MONGO_DB_NAME: "yap"
  # Add additional credentials if needed
  MONGO_USER: "yap-backend"
  MONGO_PASSWORD: "sipwid-cemnYj-doqto2"