name: Auto-approve PRs

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
